# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXbC-G81hXgh3kZuugY0qZpE0_ohiy2L
"""

!pip install sunpy[all]

import os
from google.colab import drive

# 1. Mount your personal Google Drive
drive.mount('/content/drive')

# 2. Define a clean path inside your Drive to save your FITS files permanently
drive_data_dir = '/content/drive/MyDrive/SolarData'

import os
import numpy as np
import pandas as pd
import astropy.units as u
from sunpy.net import Fido
from sunpy.net import attrs as a

# 1. Define base directory
drive_data_dir = '/content/drive/MyDrive/SolarData'
if not os.path.exists(drive_data_dir):
    os.makedirs(drive_data_dir)

# 2. Automatically generate the 20 time slots (6-hour intervals starting Nov 7)
start_time = '2020-11-07 00:00:00'
end_time = '2020-11-11 18:00:00'
timestamps = pd.date_range(start=start_time, end=end_time, freq='6h')

print(f"Total loop steps scheduled: {len(timestamps)} (from observation1 to observation{len(timestamps)})")

# 3. Loop through each timestamp automatically to download files
for index, base_time in enumerate(timestamps):
    # Dynamically generate sequential observation numbers (1, 2, 3... up to 20)
    obs_number = index + 1

    # Format current base time to string for SunPy Net attributes
    base_time_str = base_time.strftime('%Y/%m/%d %H:%M:%S')

    # Calculate the end windows: +10 seconds for AIA, +40 seconds for HMI
    aia_end_time_str = (base_time + pd.Timedelta(seconds=10)).strftime('%Y/%m/%d %H:%M:%S')
    hmi_end_time_str = (base_time + pd.Timedelta(seconds=40)).strftime('%Y/%m/%d %H:%M:%S')

    # Dynamically change the time ranges based on current step
    time_range = a.Time(base_time_str, aia_end_time_str)
    time_range_HMI = a.Time(base_time_str, hmi_end_time_str)

    # Define paths and expected final sequential names
    expected_aia_name = f"observation{obs_number}_aia.fits"
    expected_hmi_name = f"observation{obs_number}_hmi.fits"

    local_aia_path = os.path.join(drive_data_dir, expected_aia_name)
    local_hmi_path = os.path.join(drive_data_dir, expected_hmi_name)

    print(f"\n--- ⏳ Running Loop Step {obs_number} | Base Time: {base_time_str} ---")

    # ----------------- 1. DOWNLOAD AIA 193 Å -----------------
    if os.path.exists(local_aia_path):
        print(f"🚀 AIA file already exists in Google Drive: {expected_aia_name}")
    else:
        print("📡 AIA file not found locally. Searching JSOC / VSO...")
        aia_query = Fido.search(time_range, a.Instrument.aia, a.Wavelength(193*u.angstrom))

        if aia_query:
            print("📥 Fetching AIA data from server...")
            # Providing the exact name structure inside the path argument forces the rename
            Fido.fetch(aia_query, path=local_aia_path, max_conn=5)
            print(f"✅ Downloaded and saved AIA to: {local_aia_path}")
        else:
            print(f"❌ No AIA data found for time window: {base_time_str}")

    # ----------------- 2. DOWNLOAD HMI MAGNETOGRAM -----------------
    if os.path.exists(local_hmi_path):
        print(f"🚀 HMI file already exists in Google Drive: {expected_hmi_name}")
    else:
        print("📡 HMI file not found locally. Searching JSOC...")
        hmi_query = Fido.search(time_range_HMI, a.Instrument.hmi, a.Physobs.los_magnetic_field)

        if hmi_query:
            print("📥 Fetching HMI data from server...")
            # Providing the exact name structure inside the path argument forces the rename
            Fido.fetch(hmi_query, path=local_hmi_path, max_conn=5)
            print(f"✅ Downloaded and saved HMI to: {local_hmi_path}")
        else:
            print(f"❌ No HMI data found for time window: {base_time_str}")

print("\n🎉 Automation sequence complete! All files verified or securely stored in Drive.")